services:
  postgres:
    image: postgres:16
    container_name: quarkus-postgres
    environment:
      POSTGRES_DB: backend_priprema
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

    backend:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: backend_priprema
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      QUARKUS_PROFILE: docker

volumes:
  pgdata:
